### ISSUE TITLE
Add option to disable warning 'set author name as ’licenser.author’ in configuration. OS username will be used as default'

### ISSUE THREAD

**Issue by sergey-s-betke** [ymotongpoo/vsc-licenser#112]
### Expected behavior

Add option to disable warning 'set author name as ’licenser.author’ in configuration. OS username will be used as default'.

### Actual behavior

I see 'set author name as ’licenser.author’ in configuration. OS username will be used as default' warning. For multiusers project we can't set licenser.author in configuration. OS username or GitHub user name is the best choice. 

## Steps to reproduce the issue

1. Install vsc-licenser
2. don't set licenser.author in config
3. restart VSCode

**Comment by spindensity** [comment]
After setting the "licenser.author" in the configurations, the warning still appears...

**Comment by ymotongpoo** [comment]
This should be fixed by #116, #117, which is included in v1.7.1. Please let me know if you still see the issue after upgrading the package.
