### ISSUE TITLE
`licenser.author` setting is ignored when inserting header and creating license file. Default login name is always used

### ISSUE THREAD

**Issue by Swat-SomeBug** [ymotongpoo/vsc-licenser#118]
*** Please make sure to use this template to report issue. Any issue report that does not follow this template will be ignored. ***

## Runtime environment
* OS (version): Linux (Pop-OS 21.04)
* VS Code version: 1.57.1
* VS Code build number (if possible):
* other extensions installed:
  - Microsoft C/C++ extension,
  - CMake Tools,
  - CMake,
  - Git Graph,
  - Github pull requests
  - Bookmarks

You can confirm installed extensions by calling "Extensions: Show Installed Extensions", or
just click extensions tab in the case you are using VS Code 1.3+.

### Expected behavior
`licenser.author` is used when generating license file and inserting headers. `licenser.author` workspace setting should override user setting.

### Actual behavior
Both user and workspace `licenser.author` settings are ignored. Default login user name is always used.

## Steps to reproduce the issue
1. Install the plugin
2. Configure `licenser.author` and `licenser.license` workspace setting
3. From command pallet > `licenser: Insert license header`

**Comment by reporter123** [comment]
Just downgraded to 1.6 as a workaround.

**Comment by ymotongpoo** [comment]
Fixed by #116, #117
