### ISSUE TITLE
Comment type is always //

### ISSUE THREAD

**Issue by BMBurstein** [ymotongpoo/vsc-licenser#128]
Issue Type: <b>Bug</b>

I tried adding a license to a CMakeLists.txt file. VSCode knows how to comment out lines correctly (using #), but licenser adds a license using //

Extension version: 1.9.0
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-104-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (16.94GB free)|
|Process Argv|--crash-reporter-id 026754aa-b996-4f12-9e27-4c515ec2b2cc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.4.0-104-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (2 x 2495)|
|Memory (System)|3.83GB (1.12GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477cf:30450039

```

</details>

**Comment by Diyou** [comment]
Cmake support is missing. Should probably reuse the makefile style notations.
