### ISSUE TITLE
AGPLv3 is having an outdated link

### ISSUE THREAD

**Issue by valkum** [ymotongpoo/vsc-licenser#129]
*** Please make sure to use this template to report issue. Any issue report that does not follow this template will be ignored. ***

## Runtime environment
* OS (version): linux
* VS Code version: 1.65.2
* VS Code build number (if possible):
* other extensions installed: n/a

You can confirm installed extensions by calling "Extensions: Show Installed Extensions", or
just click extensions tab in the case you are using VS Code 1.3+.

### Expected behavior
The new https based link should be included in the file header part.
See here https://spdx.org/licenses/AGPL-3.0-or-later.html or https://www.gnu.org/licenses/agpl-3.0.html

### Actual behavior
The http link is present

## Steps to reproduce the issue
1. Insert AGPLv3 file header
2.
3.

**Comment by ymotongpoo** [comment]
I think now this is supported. Closing the issue.
