### ISSUE TITLE
License is getting in front of the php start tag.

### ISSUE THREAD

**Issue by jens1o** [ymotongpoo/vsc-licenser#14]
## Runtime environment
* OS (version): Windows 10
* Hardware: An really old laptop
* VS Code version: 1.8.1
* VS Code build number:
![image](https://cloud.githubusercontent.com/assets/11234139/21580863/bff691f8-d015-11e6-8b31-a8be982906e0.png)
* other extensions installed: A lot!

You can confirm installed extensions by calling "Extensions: Show Installed Extensions", or
just click extensions tab in the case you are using VS Code 1.3+. Yep.

### Expected behavior
License is entered after the php start tag

### Actual behavior
License get's entered in front of the php start tag.

![image](https://cloud.githubusercontent.com/assets/11234139/21580867/fb291598-d015-11e6-90a6-fe863d230e5d.png)

## Steps to reproduce the issue
1.  Create a php file and write the php start tag `<?php`
2. Let the license gets inserted
3.  Done!

**Comment by ymotongpoo** [comment]
This fix only supports the case where `<?php` is in the first line of the file. If you feel this fix doesn't work, please reopen this issue with more use cases.

**Comment by jens1o** [comment]
I think this will be enough. Thank you!
