### ISSUE TITLE
Do you need help maintaining this repo?

### ISSUE THREAD

**Issue by FlorentPoinsaut** [ymotongpoo/vsc-licenser#141]
Hi @ymotongpoo,
Thank you for this extension and your work!
I've noticed that there hasn't been an update in over a year.
Do you need help maintaining this repo and releasing a new version?
Thank you in advance for you answer.
Regards,

**Comment by ymotongpoo** [comment]
Hi @FlorentPoinsaut, thank you for the comment! As of today, I don't have much to add this extension but it would be great if you could upgrade the depending TS version of this repo and set up linter for it.

**Comment by FlorentPoinsaut** [comment]
OK.
How do I go about this? Do you want me to open some PR for this or grant me access to this repo?

**Comment by ymotongpoo** [comment]
That sounds perfect! Thanks!
