### ISSUE TITLE
[bug] @FILENAME@ does not substitute on linux

### ISSUE THREAD

**Issue by Diyou** [ymotongpoo/vsc-licenser#144]
## Runtime environment
* OS (version): Linux x64 6.6.1-arch1-1
* VS Code version: 1.84.2
* other extensions installed:  ms-vscode.cpptools-extension-pack

## Behaviors
Configuring settings.json with
`"licenser.customHeader": "@FILENAME@ - @PROJECT@\n\nCopyright (c) @YEAR@ @AUTHOR@",`
on linux writes something like in cpp file
```cpp
/**
 * @FILENAME@ - MyProject
 *
 * Copyright (c) 2023 Author
 */
```

### Expected behavior
Should print:
```cpp
/**
 * MyHeader.h - MyProject
 *
 * Copyright (c) 2023 Author
 */
```

## Steps to reproduce the issue
1. Configure settings.json with `licenser.customHeader`
2. Insert license header

**Comment by Diyou** [comment]
https://github.com/ymotongpoo/vsc-licenser/blob/d182244b563efae3d788a13ff1abf0b2e41b8c56/src/extension.ts#L326

Might need to use
```ts
path.posix
```
when not on windows.

**Comment by Diyou** [comment]
Tested with 1.10.0 and it's still behaving like that.

**Comment by Diyou** [comment]
Looks like its an error in the Readme. Using %FILE% instead of %FILENAME% works.

**Comment by ymotongpoo** [comment]
Thanks for reporting. This is a documentation bug. I added the fix to the doc. It should be included in the next release.
