### ISSUE TITLE
sort Insert License Header before Create License FIle

### ISSUE THREAD

**Issue by jrobeson** [ymotongpoo/vsc-licenser#21]
## Runtime environment
* OS (version): Fedora 25
* Hardware: not sure
* VS Code version: 1.9.0
* VS Code build number: ?
* other extensions installed:  rust,  php intellisense, c/c++, python

### Expected behavior
I'd like to see "Insert License Header" sort first in the command palatte, as it is likely the commonly used option.
### Actual behavior
Currently "Create License Header" sorts first in the command palette.

Of course, if this is the intended behavior, then feel free to close the ticket.

**Comment by ymotongpoo** [comment]
@jrobeson thank you for filing this. your suggestion makes sense to me, but I couldn't find any option to register the command in an arbitrary order.
https://code.visualstudio.com/Docs/extensionAPI/vscode-api

I welcome the pull-request on this if you find a solution. leaving this opened for visibility.

**Comment by ymotongpoo** [comment]
Closed this issue as no options is available to achieve this.
