### ISSUE TITLE
allow injecting a license that is the not the same as the project license.

### ISSUE THREAD

**Issue by jrobeson** [ymotongpoo/vsc-licenser#22]
It'd be nice if you could also inject a specific license by name. My project is multilicensed. Most of the application stuff is AGPL 3.0, but I'd like to make some of the libraries MIT or ASL 2.0.

I'm not sure how the interface should be though.

**Comment by ymotongpoo** [comment]
To reduce my cost to read all issues raised, please follow the format for any issues from next time. This is the comment from issue template.

> *** Please make sure to use this template to report issue. Any issue report that does not follow this template will be ignored. ***

**Comment by bkeys** [comment]
I would also like to add on and say that I would like to see this functionality implemented as well

**Comment by ymotongpoo** [comment]
Released 0.5.3. Now you can insert arbitrary license by calling "licenser: Arbitrary license header" command. Enjoy!
