### ISSUE TITLE
Custom Copyright Text

### ISSUE THREAD

**Issue by abakirov2** [ymotongpoo/vsc-licenser#23]
Sorry for not using a template as this is not really a bug report but rather a question or enhancement request.

This extension is very cool! The best of ones I explored. It only seems to lack support for custom copyright text. I want to add headers like `COPYRIGHT <year> MY COMPANY blah blah blah`. Do you plan to support this or maybe already do in some hidden way?

**Comment by ymotongpoo** [comment]
No worries, @abakirov2. Thanks for the request and your warm message. Currently this extension doesn't support any custom text, but this sounds fairly useful idea to me as well, so I labeled as "enhancement" for future work.
