### ISSUE TITLE
Add license headers to multiple files in a directory

### ISSUE THREAD

**Issue by anandanand84** [ymotongpoo/vsc-licenser#32]
This is more of a question or enhancement request, Is there any way to add license to all files in the entire project?

**Comment by ymotongpoo** [comment]
Currently the feature is not implemented yet. Can you provide your demands in details?

**Comment by anandanand84** [comment]
For example, if I want to add a AGPLV3 license, to the entire project with lot of files, currently I have to open every file and add the license header, thought instead if I point it to a folder or rott it will update all files with the license header

**Comment by ymotongpoo** [comment]
Thanks. Triaged this as FR.

**Comment by saikirankumar-revanuru** [comment]
> Thanks. Triaged this as FR.

Hi @ymotongpoo . Is this feature available now? Can we add header to multiple files with a single command?

**Comment by ymotongpoo** [comment]
No, we can't yet. I welcome the pull requests for this issue.
