### ISSUE TITLE
Random JS functions appear when inserting at the top of file 

### ISSUE THREAD

**Issue by fantasticfears** [ymotongpoo/vsc-licenser#37]
## Runtime environment
* OS (version): macOS 10.12.6
* VS Code version: 1.17.2
* VS Code build number (if possible): b813d12980308015bcd2b3a2f6efa5c810c33ba5
* other extensions installed: DevonDCarew.bazel-code,DotJoshJohnson.xml,EditorConfig.EditorConfig,HookyQR.beautify,James-Yu.latex-workshop,Lencerf.beancount,PeterJausovec.vscode-docker,RolandGreim.sharecode,Zignd.html-css-class-completion,adamvoss.vscode-languagetool,adamvoss.vscode-languagetool-en,adamvoss.vscode-languagetool-zh,ban.spellright,codezombiech.gitignore,dbaeumer.vscode-eslint,deerawan.vscode-dash,donjayamanne.jupyter,donjayamanne.python,eamodio.gitlens,emmanuelbeziat.vscode-great-icons,formulahendry.code-runner,georgewfraser.vscode-javac,lukehoban.Go,mrmlnc.vscode-scss,ms-vscode.cpptools,oderwat.indent-rainbow,rebornix.Ruby,robinbentley.sass-indented,tcwalther.cython,tht13.rst-vscode,twxs.cmake,unbug.codelf,vscodevim.vim,xaver.clang-format,ymotongpoo.licenser,zxh404.vscode-proto3,

### Expected behavior
Inject the correct header 

### Actual behavior
Inject the license with two functions: (ex. Cpp file)
```
 *function (comparer) {
    for (var i = 0; i < this.length; i++) {
        if (comparer(this[i])) return true;
    }
    return false;
}
 *function (element, compare) {
    if (!this.inArray(compare)) {
        this.push(element);
    }
}```

## Steps to reproduce the issue
1. User setting `"licenser.author": "Erick `Xiao` Guan"`, workspace setting ``` "licenser.projectName": "markrouge",
    "licenser.license": "AL2",
    "licenser.useSingleLineStyle": false
}```
2. Insert license header

**Comment by ymotongpoo** [comment]
I feel sorry but I can't reproduce this now. I mark this as 'need repro report'

**Comment by caipre** [comment]
I was having this same problem and went through my installed extensions one-by-one to find that [SpellRight](https://github.com/bartosz-antosik/vscode-spellright) is the culprit. I'm not sure what causes the problem, but disabling that extension has resolved this for me.

**Comment by Alexendoo** [comment]
I too experience this when spellright is enabled
