### ISSUE TITLE
Add config to prevent automatic header insertion

### ISSUE THREAD

**Issue by MisLink** [ymotongpoo/vsc-licenser#41]
Sometimes I do not need to automatically insert a header every new file is created, and I think a configuration item is needed to control it.

**Comment by franher** [comment]
@ymotongpoo look like this feature is not released into the VSCode Studio plugin yet (https://marketplace.visualstudio.com/items?itemName=ymotongpoo.licenser)

Some idea when it could happen? Thank you so much

**Comment by ymotongpoo** [comment]
@franher thanks for the heads up. I just forgot to release it. I just published the new version 1.1.2 and it should work.

**Comment by franher** [comment]
@ymotongpoo thank you! I just installed the new version 💪 :)
