### ISSUE TITLE
Placeholder gets replaced only once

### ISSUE THREAD

**Issue by bbalvanera** [ymotongpoo/vsc-licenser#44]
*** Please make sure to use this template to report issue. Any issue report that does not follow this template will be ignored. ***

## Runtime environment
* OS (version): Windows 10 Home
* VS Code version: 1.21.0
* VS Code build number (if possible):
* other extensions installed: none

You can confirm installed extensions by calling "Extensions: Show Installed Extensions", or
just click extensions tab in the case you are using VS Code 1.3+.

## Behaviors
When using a custom header with placeholders, only one instance of each placeholder gets replaced.

### Expected behavior
All instances of the same placeholder get replace with same value from `settings.json`

### Actual behavior
Only the first instance of a placeholder gets replaced.

## Steps to reproduce the issue
1. Set licenser.author. Set licenser.license to `Custom`. Set licenser.projectName. Set licenser.customHeader to "Copyright (C) @YEAR@ @AUTHOR@\n\nThis file is part of @PROJECT@.\n\n@PROJECT@ is a free software;..."
2. Open any file without a license header
3. Ctrl + Shift + P and select `licenser: Insert license header

**Comment by ymotongpoo** [comment]
fixed in #45.
