### ISSUE TITLE
command 'extension.anyLicenseHeader' not found

### ISSUE THREAD

**Issue by akshita31** [ymotongpoo/vsc-licenser#46]
*** Please make sure to use this template to report issue. Any issue report that does not follow this template will be ignored. ***

## Runtime environment
* OS (version): Windows 10
* VS Code version: 1.23.0
* VS Code build number (if possible):
* other extensions installed: C#, tslint

You can confirm installed extensions by calling "Extensions: Show Installed Extensions", or
just click extensions tab in the case you are using VS Code 1.3+.

## Behaviors
Ctrl+Shit+p --> "licenser: Arbitrary license header"
### Expected behavior
Something happens

### Actual behavior
error is displayed as above

## Steps to reproduce the issue
1.  Install the extension from the marketplace
2. Ctrl+Shit+p --> "licenser: Arbitrary license header"

**Comment by ibraimgm** [comment]
Take a look at Pull Request #56, it fixes the problem.

Note that if PR #55 is accepted, the UI can be later improved to show a list of available licenses.
