### ISSUE TITLE
Add support for Dart

### ISSUE THREAD

**Issue by 12people** [ymotongpoo/vsc-licenser#62]
Please add support for the Dart language. It's very similar to Java, it should be fairly easy to port the Java solution over to work with Dart.

**Comment by 12people** [comment]
Nevermind, Dart seems to be supported anyway. That said, it'd still be nice to see it in the list of supported languages.

**Comment by ymotongpoo** [comment]
Oh, does it support Dart already? I don't see it in the list.
https://github.com/ymotongpoo/vsc-licenser/blob/develop/src/notation.ts#L64-L107

If you can make the pull request for Dart support, I appreciate it.
