### ISSUE TITLE
Add 0BSD license

### ISSUE THREAD

**Issue by freemin7** [ymotongpoo/vsc-licenser#80]
https://opensource.org/licenses/0BSD

**Comment by tevosouza** [comment]
Hello @freemin7,
I've made a PR to close this issue!

**Comment by freemin7** [comment]
Thanks, if would prefer it to say 
> 
> Use of this source code is governed by a public domain
> equivalent license that can be found in the LICENSE file.`;

As public domain equivalent is a stronger statement than BSD style.

However you can push it as it is now and close the issue as you see fit.

**Comment by ymotongpoo** [comment]
Fixed in #81
