### ISSUE TITLE
"Insert license headers to contents" command not showing

### ISSUE THREAD

**Issue by mkatliar** [ymotongpoo/vsc-licenser#84]
## Runtime environment
* OS (version): Ubuntu 20.04.1 LTS 64-bit
* VS Code version: 1.48.2
* VS Code build number (if possible):
* other extensions installed:
13xforever.language-x86-64-assembly
ban.spellright
bbenoist.Doxygen
DavidSchuldenfrei.gtest-adapter
donjayamanne.githistory
eamodio.gitlens
hbenl.vscode-test-explorer
James-Yu.latex-workshop
joaompinto.vscode-graphviz
julialang.language-julia
matepek.vscode-catch2-test-adapter
mikestead.dotenv
mine.cpplint
mitaki28.vscode-clang
ms-python.python
ms-vscode.cmake-tools
ms-vscode.cpptools
mxschmitt.postscript
nobuhito.printcode
pdconsec.vscode-print
shd101wyy.markdown-preview-enhanced
shigma.vscode-wl
sidneys1.gitconfig
slevesque.vscode-hexdump
torn4dom4n.latex-support
twxs.cmake
vsciot-vscode.vscode-arduino
ymotongpoo.licenser
zxh404.vscode-proto3

### Expected behavior
Pop-up list of commands contains "Insert license headers to contents"

### Actual behavior
Pop-up list of commands does not contain "Insert license headers to contents"
![image](https://user-images.githubusercontent.com/8616371/92129830-b2806a80-ee0c-11ea-8baf-a4c110b845ca.png)

## Steps to reproduce the issue
1. Go to the Command Palette
2. Type 'licenser'

**Comment by ToastHawaii** [comment]
I found the command in the context menu by right click on a folder in the VS Code Explorer. Does this work for you?

**Comment by tevosouza** [comment]
Hi @mkatliar 
I made a PR #99 that add the capability to add the license header to all files into the workspace.
![image](https://user-images.githubusercontent.com/58958299/106345582-10b45b00-6290-11eb-8aad-9fd435381845.png)
