### ISSUE TITLE
Create LICENSE with AL2 doesn't replace author name and date.

### ISSUE THREAD

**Issue by jmhodges** [ymotongpoo/vsc-licenser#86]
## Runtime environment
* OS (version): macOS
* VS Code version: 1.49.0

* VS Code build number (if possible): Commit: e790b931385d72cf5669fcefc51cdf65990efa5d

* other extensions installed: 

You can confirm installed extensions by calling "Extensions: Show Installed Extensions", or
just click extensions tab in the case you are using VS Code 1.3+.

### Expected behavior

Creating a LICENSE with `Create LICENSE file` with AL2 set in the settings should replace the `Copyright [yyyy] [name of copyright owner]` with the current year and the name of the author. This happens even after reloading the window.

### Actual behavior

The line `Copyright [yyyy] [name of copyright owner]` remains as it is in the template.

## Steps to reproduce the issue
1. Select AL2 in the User settings of the licenser extension
2. Add a name as the author in the User settings.
3. Reload the window
4. Run `Create LICENSE file`.

**Comment by ymotongpoo** [comment]
As commented in #87, the part you mention is the license header template in Appendix, which is expected.
