### ISSUE TITLE
SPDX License identifier option 

### ISSUE THREAD

**Issue by jmhodges** [ymotongpoo/vsc-licenser#88]
It would be nice if we could say we prefer to have the SPDX license identifier used as our file headers.

Those are things like: 

```
// Copyright 2020 Jeff Hodges
// SPDX-License-Identifier: Apache-2.0
```

and are documented at https://spdx.org/licenses/

**Comment by tevosouza** [comment]
Hi @jmhodges!
I'm on it

Config:
![image](https://user-images.githubusercontent.com/58958299/105622095-2f78a480-5ded-11eb-940c-40cff061d3ae.png)

Results:
![image](https://user-images.githubusercontent.com/58958299/105622117-5c2cbc00-5ded-11eb-99a9-0e4090425a06.png)
