### ISSUE TITLE
licenser.customHeaderFile only works with absolute file path

### ISSUE THREAD

**Issue by mnesarco** [ymotongpoo/vsc-licenser#93]
## Runtime environment
* OS (version): Linux Mint 19.3
* VS Code version: 1.52.1
* VS Code build number (if possible): ea3859d4ba2f3e577a159bc91e3074c5d85c0523
* other extensions installed: tons of extensions

### Expected behavior

`licenser.customHeaderFile` should allow to specify a path relative to project dir or resolve `${workspaceFolder} `

### Actual behavior

Only works with absolute file path

## Steps to reproduce the issue
Define `licenser.customHeaderFile` setting in `.vscode/settings.json`:

```
{
    "licenser.customHeaderFile": "${workspaceFolder}/.vscode/license-template.txt",
    "licenser.license": "Custom"
}

```

**Comment by tevosouza** [comment]
Hi @mnesarco 
I made a pull-request adding this feature. 
I hope that works for you =)
