### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mnesarco** [ymotongpoo/vsc-licenser#97]
## Runtime environment
* OS (version): Linux Mint 19.3
* VS Code version: 1.52.1
* VS Code build number (if possible): ea3859d4ba2f3e577a159bc91e3074c5d85c0523
* other extensions installed: Many

Hi Friends, There are many interesting changes merged since 1.5.0, is there a plan to release a version soon?

Thank you for this great Extension.

**Comment by ymotongpoo** [comment]
thanks for reaching out. now it is 1.7.1.
