### ISSUE TITLE
Auto header insertion not working at startup because extension is not activated until licenser command issued manually

### ISSUE THREAD

**Issue by drtyh2o** [ymotongpoo/vsc-licenser#98]
*** Please make sure to use this template to report issue. Any issue report that does not follow this template will be ignored. ***

## Runtime environment
* OS (version): MacOS 11.1
* VS Code version: 
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```
## Behaviors
When launching VS Code, auto header insertion does not work until a `licenser` command is issued manually to activate the extenstion.

### Expected behavior
Extension should be active and insert headers automatically following startup.

### Actual behavior
A `licenser` command must be executed manually before auto insertion is enabled.

## Steps to reproduce the issue
1. Launch VS Code
2. Create a new file (header is not inserted)
3. Manually run "licenser: Insert license header"
4. Create another new file (header is inserted automatically)

VS Code supports an `onStartupFinished` [activation event](https://code.visualstudio.com/api/references/activation-events#onStartupFinished) which could perhaps be used:
```
"activationEvents": [
    "onStartupFinished"
]
```

**Comment by tevosouza** [comment]
Hi @drtyh2o, How are u?
I think that this problem occurs because the activate method is not implemented yet, I'll take a look when I have some time.

**Comment by drtyh2o** [comment]
> I think that this problem occurs because the activate method is not implemented yet, I'll take a look when I have some time.

I took a peek at the code and there is an `activate` method (I think one is required). I modified the `package.json` of my local installation as above and the extension activates during startup and automatic header insertion works. Thanks for looking into this. Cool extension!
